version: '3'

services:
  app:
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    depends_on:
      - db    

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    image: nginx-node:prod
    build:
      context: ./nginx
    container_name: nginx-node
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  node-network: 
    driver: bridge
